#!/usr/bin/env perl

use strict;
use warnings;

use feature 'say';

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/lib" }

# my $USERDIR = abs_path(dirname($0) . "/users");
# $USERDIR =~ s/^\Q$ENV{PWD}\E/./; # relative path
# mkdir $USERDIR and say "info: created directory $USERDIR" unless -d $USERDIR;

use Cwd 'abs_path';
use File::Basename;
use BeerPlusPlus::Database;
$BeerPlusPlus::Database::DATADIR = abs_path(dirname($0) . "/db");

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('BeerPlusPlus');
