=pod

=head1 NAME

BeerPlusPlus - Simple beer storage application

=head1 INSTALLATION

makefile comming soon...

=head1 USAGE

Run application on Mojolicious test server available at localhost:3000

    ./beer++

To run the application for development purposes start morbo as follows:

    morbo -w templates/ -w public/ -w lib/ beer++

In this case morbo listens to changes on each specified directory plus the
application script.

=cut

