#! /bin/bash

function _beer_complete_options() {
	COMPREPLY=( $(compgen -W "--help" -- "$cur") )
}

function _beer_complete_subcmds() {
	local PERL5LIB="$(dirname $BASH_SOURCE)/../lib:$PERL5LIB"
#	COMPREPLY=( $(compgen -W "$(perl -MBeerPlusPlus::Command=commands \
#			-E 'say join "\n", map { $_->name } commands')" -- "$cur") )
	COMPREPLY=( $(compgen -W "start help git stock" -- "$cur") )
}

function _beer_complete_store() {
	local base="$(dirname "$BASH_SOURCE")/../db/$1"
	COMPREPLY=( $(compgen -W "$(ls "$base/*.json" \
			| perl -pe 's/\.json$//')"-- "$cur") )
}

function _beer_complete_stores() {
	local base="$(dirname "$BASH_SOURCE")/../db"
	COMPREPLY=( $(compgen -W "$(ls "$base")" -- "$cur") )
}

function _beer_complete_git() {
	COMP_WORDS=( ${COMP_WORDS[1]} ${COMP_WORDS[@]:3:COMP_CWORD} )
	COMP_CWORD=$(($COMP_CWORD - 2))
	_git
}

function _beer() {
	local cur=${COMP_WORDS[COMP_CWORD]}
	local prev=${COMP_WORDS[COMP_CWORD -1]}

	if [ $COMP_CWORD -eq 1 ]; then
		case "$cur" in
			-*)
				_beer_complete_options
				;;
			*)
				_beer_complete_subcmds
				;;
		esac
	else
		local cmd=${COMP_WORDS[1]}
		case "$cmd" in
			stock)
				_beer_complete_store stocks
				;;
			git)
				if [ $COMP_CWORD -eq 2 ]; then
					_beer_complete_stores
				else
					_beer_complete_git
				fi
				;;
			help)
				_beer_complete_subcmds
				;;
			*)
				if declare -f _beer_$cmd &> /dev/null; then
					_beer_$cmd
				fi
				;;
		esac
	fi
}

complete -F _beer beer++

