#! /bin/bash

for completion in "$(dirname "$BASH_SOURCE")"/beer++completion.*; do
	. "$completion"
done
unset completion


function _beer_complete_options() {
	COMPREPLY=( $(compgen -W "--help" -- "$cur") )
}

#
# usage: _beer_complete_files <path> [suffix]
#
# * suffix is removed automatically (this is due it is most used case)
# * if searching for some files and suffix should not be removed simple
#   append it after calling this function:
#
#	  _beer_complete_files db/users "$suffix"
#     COMPREPLY=( "${COMPREPLY[@]/#/$suffix}" )
#
#   for example to search for 'user' which is actual 'user.json' but
#   leave suffix '.json':
#
#	  _beer_complete_files db/users '\.json'
#     COMPREPLY=( "${COMPREPLY[@]/%/.json}" )
#
#   to apply parameter expansion before compgen is called simply specify
#   them after the suffix, e.g.
#
#     # lowercase the found filenames and prepend 'x' to each result
#     _beer_complete_files lib/BeerPlusPlus/Command .pm ',*' '/#/x'
#
# * result is APPENDED to COMPREPLY array
#
function _beer_complete_files() {
	local dir="$(dirname $BASH_SOURCE)/../$1"
	local suffix=$2
	shift 2

	local IFS=$'\n'
	local files=( $(ls "$dir" | grep -Po "^.+(?=$suffix$)") )
	while [ $# -gt 0 ]; do
		eval "files=( \"\${files[@]$1}\" )"
		shift
	done

	COMPREPLY+=( $( compgen -W "${files[*]}" -- "$cur") )
}

function _beer_complete_commands() {
	_beer_complete_files lib/BeerPlusPlus/Command .pm ',*' # lowercase
}

function _beer_complete_store() {
	_beer_complete_files "db/$1" '\.json'
}

function _beer_complete_stores() {
	_beer_complete_files db
}

function _beer_complete_cmd_help() {
	_beer_complete_commands
}

function _beer() {
	local cur=${COMP_WORDS[COMP_CWORD]}
	local prev=${COMP_WORDS[COMP_CWORD -1]}

	if [ $COMP_CWORD -eq 1 ]; then
		case "$cur" in
			-*)
				_beer_complete_options
				;;
			*)
				_beer_complete_commands
				;;
		esac
	else
		local cmd=${COMP_WORDS[1]}
		if declare -F _beer_complete_cmd_"$cmd" > /dev/null; then
			_beer_complete_cmd_"$cmd" "$@"
		else
			COMPREPLY=( $(compgen -o default) )
		fi
	fi
}

complete -F _beer beer++

