#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use Mojo::JSON;
use Digest::SHA1 qw(sha1_base64);

my $USERDIR = "../users";
mkdir $USERDIR unless -d $USERDIR;

sub create_users
{
	my @usernames = @_;
	for my $username (@usernames) {
		my $pass = sha1_base64('lukeichbindeinvater');
		my %new_user = (
			pass => $pass,
			user => $username,
			counter => 0,
		);
		my $json = Mojo::JSON->new;
		my $data = $json->encode(\%new_user);
		open my $fh, '>', "$USERDIR/$username".".json" or die qq/cannot open file $!/;
		print {$fh} $data;
		close $fh;
	}
}

# TODO
# better handling of commandline arguments
# start webapplication just once
if (@ARGV) {
	create_users(@ARGV);
}

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('BeerPlusPlus');
