#! /usr/bin/env perl

#use v5.14; # due to shift $ref

use strict;
use warnings;

use feature 'say';


use BeerPlusPlus::Stock ':vars';
use BeerPlusPlus::User;
use BeerPlusPlus::Billing;

use Data::Printer;


my %bills = BeerPlusPlus::Billing->calculate();

